CREATE DATABASE BD_MATRICULA

USE BD_MATRICULA

CREATE TABLE ESTUDIANTES(
id_estudiante INT PRIMARY KEY 
)

CREATE TABLE MATRICULA(
id_matricula INT PRIMARY KEY
)

CREATE TABLE PENSIONES(
id_PENSIONES INT PRIMARY KEY
)