CREATE DATABASE BD_MATRICULA

USE BD_MATRICULA

CREATE TABLE ESTUDIANTE(
id_estudiante	INT PRIMARY KEY,
dni				VARCHAR(8) NOT NULL,
nombres			VARCHAR(50) NOT NULL,
apellidos		VARCHAR(50) NOT NULL,
telefono		VARCHAR(9) NOT NULL
)

CREATE TABLE MATRICULA(
id_matricula		INT PRIMARY KEY,
id_estudiante		INT NOT NULL,
nivel				VARCHAR(50) NOT NULL,
monto_matricula		MONEY NOT NULL,
fecha_m				DATE NOT NULL,

FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTE(id_estudiante)
)

CREATE TABLE PENSION(
id_pensiones		INT PRIMARY KEY,
id_estudiante		INT NOT NULL,
n_pension			INT NOT NULL,
monto				MONEY NOT NULL,
fecha_p				DATE NOT NULL,

FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTE(id_estudiante)
)
