CREATE DATABASE BD_MATRICULA

USE BD_MATRICULA

CREATE TABLE ESTUDIANTES(
id_estudiante INT PRIMARY KEY,
dni VARCHAR(8) NOT NULL,
nombre VARCHAR(8) NOT NULL,
)

CREATE TABLE PENSIONES(
id_PENSIONES INT PRIMARY KEY,
monto DECIMAL(10, 2),
fecha_pago DATE,
estado_pago VARCHAR(20),
id_estudiante INT,
FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTES(id_estudiante)
);


CREATE TABLE MATRICULA(
id_matricula INT PRIMARY KEY
)

CREATE TABLE FACTURA(
id_factura INT PRIMARY KEY
)