//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTES
    {
        public ESTUDIANTES()
        {
            this.FACTURA = new HashSet<FACTURA>();
            this.MATRICULA = new HashSet<MATRICULA>();
            this.PENSIONES = new HashSet<PENSIONES>();
        }
    
        public int id_estudiante { get; set; }
        public string dni { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string codigo { get; set; }
        public string correo { get; set; }
    
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
        public virtual ICollection<PENSIONES> PENSIONES { get; set; }
    }
}
