//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int id_factura { get; set; }
        public int id_estudiante { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public decimal mora { get; set; }
        public decimal monto_total { get; set; }
    
        public virtual ESTUDIANTES ESTUDIANTES { get; set; }
    }
}
